#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

echo "🔎 Running tests before push..."
yarn cli test || echo "⚠️ cli tests failed, but code will still be pushed."
yarn utils test || echo "⚠️ utils tests failed, but code will still be pushed."
yarn core test || echo "⚠️ core tests failed, but code will still be pushed."

exit 0
